# Generated by Django 3.1.4 on 2021-03-03 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210303_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Value'),
        ),
    ]
