# Generated by Django 3.1.4 on 2021-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210303_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesend',
            name='addres',
            field=models.CharField(max_length=300, verbose_name='Addres'),
        ),
        migrations.AlterField(
            model_name='salesend',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='salesend',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='salesend',
            name='cp',
            field=models.CharField(max_length=10, verbose_name='C.P'),
        ),
    ]
