# Generated by Django 3.1.4 on 2021-03-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210304_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('name', 'brand')},
        ),
    ]
