# Generated by Django 3.1.4 on 2021-02-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210219_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genero',
            new_name='gender',
        ),
    ]
